/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://maven.aliyun.com/repository/public")
    }
}

dependencies {
    api(libs.org.apache.pdfbox.pdfbox)
    api(libs.org.openqa.selenium.webdriver.webdriver.common)
    api(libs.org.openqa.selenium.webdriver.webdriver.support)
    api(libs.org.apache.poi.poi.ooxml)
    api(libs.net.java.dev.jna.jna)
    api(libs.net.java.dev.jna.platform)
    testImplementation(libs.junit.junit)
}

group = "com.blue"
version = "1.0-SNAPSHOT"
description = "pdfutil"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}